# 3. 도형 그리기

## 빈 스케치북 만들기

In [1]:
import cv2
import numpy as np

# 세로 480 X 가로 640, 3 Channel에 해당하는 스케치북 만들기

img = np.zeros((480, 640, 3), dtype=np.uint8)
img[:] = (255,255,255) # 흰색으로 채우기
print(img)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


### 일부 영역 색칠

In [2]:
import cv2
import numpy as np

# 세로 480 X 가로 640, 3 Channel에 해당하는 스케치북 만들기

img = np.zeros((480, 640, 3), dtype=np.uint8)
img[100:400:3, 200:600:3] = (255,255,255) # 흰색으로 채우기
print(img)

cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


## 직선
직선의 종류 (line type)

1. cv2.LINE_4: 상하좌우 4 방향으로 연결된 선
2. cv2.LINE_8: 대각선을 포함한 8 방향으로 연결된 선 (기본값)
3. cv2.LINE_AA: 부드러운 선(anti-aliasing)

In [ ]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (0,255,255) #BGR : YELLOW
THICKNESS = 3 # 두께

cv2.line(img, (50, 100), (400, 50), COLOR, THICKNESS, cv2.LINE_8)
# 그릴 위치, 시작 점, 끝 점, 색, 두께, 선 종류
cv2.line(img, (50, 200), (400, 150), COLOR, THICKNESS, cv2.LINE_4)
cv2.line(img, (50, 300), (400, 250), COLOR, THICKNESS, cv2.LINE_AA)


cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

### 원

In [ ]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (255,255,0) #BGR : YELLOW
RADIUS = 50 # 반지름
THICKNESS = 10 # 두께

cv2.circle(img, (50, 100), WRADIUS, COLOR, THICKNESS, cv2.LINE_8)
# 그릴 위치, 중심 점, 반지름, 색, 두께, 선 종류
cv2.circle(img, (100, 200), RADIUS, COLOR, cv2.FILLED, cv2.LINE_AA)


cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

### 사각형

In [ ]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (255,255,0) #BGR : YELLOW
THICKNESS = 2 # 두께

cv2.rectangle(img, (50, 100), (200, 200) COLOR, THICKNESS)
# 그릴 위치, 왼쪽 위, 오른쪽 아래, 색, 두께, 선 종류
cv2.rectangle(img, (300, 100), (400,300) COLOR, cv2.FILLED)


cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()

### 다각형

In [11]:
import cv2
import numpy as np

img = np.zeros((480, 640, 3), dtype=np.uint8)

COLOR = (255,255,0) #BGR : YELLOW
THICKNESS = 2 # 두께

pts1 = np.array([[100,100],[200,100],[150,180]])
pts2 = np.array([[200, 100],[300,100],[300,200]])

cv2.polylines(img, [pts1], True, COLOR, THICKNESS, cv2.LINE_AA)
cv2.polylines(img, [pts2], True, COLOR, THICKNESS, cv2.LINE_AA)
# True -> 닫힘, False -> 열림
# 그릴 위치, 점의 위치 리스트, 닫힘 여부, 색, 두께, 선 종류

cv2.polylines(img, [pts1, pts2], True, COLOR, THICKNESS, cv2.LINE_AA)
# 그릴 위치, 점의 위치 리스트, 닫힘 여부, 색, 두께, 선 종류(위의 두개 합친 것과 같은 결과)

pts3=np.array([[[100,300],[200,300],[100,400]],[[200,300],[300,300],[300,400]]])
cv2.fillPoly(img, pts3, COLOR, cv2.LINE_AA)

cv2.imshow('img', img)
cv2.waitKey()
cv2.destroyAllWindows()